services:
  - type: web
    name: menstrual-backend
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
